# Parameters for DrGinsInterface and ESKF initialization
# Frame ids
base_frame_id: "map"
child_frame_id: "base_link"

# Data source
use_file_data: false                # true = replay from file, false = subscribe to ROS topics
data_file_path: "/home/geneta/project/dr_gins_ws/src/dr_gins/data/527-8.csv" # imu_pose.txt用于测试

# # Replay behavior (only used when use_file_data = true)
# replay:
#   simulate_realtime: true          # if true, ReplayFromFile will sleep between samples
#   speedup: 1.0                     # >1.0 speeds up replay (dt /= speedup)

# Topics (used when not using file data)
imu_topic: "/dvs/imu"
gnss_topic: "/ublox/navpvt"

publish:
  odom_topic: "/dr_gins/odometry"
  path_topic: "/dr_gins/path"
  truth_odom_topic: "/dr_gins/truth_odometry"    # 新增
  truth_path_topic: "/dr_gins/truth_path"        # 新增
  path_buffer_size: 1000

# Initial nominal state
initial_state:
  position: [0, 0, 0]        # ENU or local frame origin (m)
  velocity: [-0.135601121298, 1.577992061167, 0.005000368718]        # m/s 伪初始状态，真初始状态由GNSS给出
  orientation_wxyz: [1, 0, 0, 0]  # quaternion w,x,y,z 伪初始状态，真初始状态由航向对齐结果给出
  accel_bias: [0.15696, 0.15696, 0.15696]      # m/s^2
  gyro_bias: [0.0069, 0.0069, 0.0069]       # rad/s
  gravity: [0.0, 0.0, -9.80191]       # m/s^2

# Initial covariance (P) settings
initial_covariance:
  pos: [10.0, 10.0, 10.0]          # 位置不确定性 (m^2)
  vel: [1.0, 1.0, 1.0]             # 速度不确定性 ((m/s)^2)
  att: [0.1, 0.1, 0.1]             # 姿态不确定性 (rad^2)
  bg: [0.01, 0.01, 0.01]           # 陀螺仪零偏不确定性 ((rad/s)^2)
  ba: [0.1, 0.1, 0.1]              # 加速度计零偏不确定性 ((m/s^2)^2)
  g: [0.01, 0.01, 0.01]            # 重力不确定性 ((m/s^2)^2)

# Q noise settings
gyro_noise: 0.000006505                 # per-axis gyro noise (used to form 3x3 diag) 假设每个轴的噪声相同 (rad/s)² / Hz
accel_noise: 0.00000841                   # per-axis accel noise (used to form 3x3 diag)   (m/s²)² / Hz

# R noise settings
gnss_noise: [1.2, 1.2, 1.2,        # GNSS measurement position noise (east,north,up) m
             2.0, 2.0, 2.0]        # GNSS measurement velocity noise (east,north,up) m/s